# Form implementation generated from reading ui file 'AddMember.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector as mc

class AddMembro_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 450)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_nome = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_nome.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_nome.setFont(font)
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.verticalLayout.addWidget(self.lineEdit_nome)
        self.lineEdit_cpf = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_cpf.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_cpf.setFont(font)
        self.lineEdit_cpf.setObjectName("lineEdit_cpf")
        self.verticalLayout.addWidget(self.lineEdit_cpf)
        self.lineEdit_telefone = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_telefone.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_telefone.setFont(font)
        self.lineEdit_telefone.setObjectName("lineEdit_telefone")
        self.verticalLayout.addWidget(self.lineEdit_telefone)
        self.lineEdit_email = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_email.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_email.setFont(font)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.verticalLayout.addWidget(self.lineEdit_email)
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color:gray;\n"
"color:white\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.label_result = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.pushButton.clicked.connect(self.inserir_membro)

    def inserir_membro(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="biblioteca"
            )
            nome = self.lineEdit_nome.text()
            cpf = self.lineEdit_cpf.text()
            telefone = self.lineEdit_telefone.text()
            email = self.lineEdit_email.text()

            if nome=="" or cpf=="" or telefone=="" or email=="":
                self.label_result.setText("Por favor preencha todos os campos")
                self.label_result.setStyleSheet('color:red')
                return
            
            mycursor = mydb.cursor()
            query = "INSERT INTO membros (cpf, nome, telefone, email) VALUES (%s,%s,%s,%s)"
            values = (cpf, nome, telefone, email)
            mycursor.execute(query, values)
            mydb.commit()
            self.label_result.setText("Livro adicionado com sucesso!")
            self.label_result.setStyleSheet('color:green')

            self.lineEdit_cpf.setText("")
            self.lineEdit_nome.setText("")
            self.lineEdit_telefone.setText("")
            self.lineEdit_email.setText("")

        except mc.Error as e:
            print("Error", e)
            self.label_result.setText("Erro ao adicionar!")
            self.label_result.setStyleSheet('color:red')


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Member"))
        self.lineEdit_nome.setPlaceholderText(_translate("Dialog", "Nome Completo"))
        self.lineEdit_cpf.setPlaceholderText(_translate("Dialog", "CPF"))
        self.lineEdit_telefone.setPlaceholderText(_translate("Dialog", "Telefone"))
        self.lineEdit_email.setPlaceholderText(_translate("Dialog", "Email"))
        self.pushButton.setText(_translate("Dialog", "Adicionar"))

