# Form implementation generated from reading ui file 'ViewMembers.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QTableWidgetItem
import mysql.connector as mc

class ViewMembros_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 450)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.tableWidget = QtWidgets.QTableWidget(parent=Dialog)
        self.tableWidget.setStyleSheet("QTableWidget{\n"
"background-color:rgb(218,218,218);\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(140)
        self.verticalLayout.addWidget(self.tableWidget)
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color:rgb(218,218,218)\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.listar_membros()
        self.lineEdit.returnPressed.connect(self.buscar_membro)

    def listar_membros(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="biblioteca"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT cpf, nome, telefone, email FROM membros")
            res = mycursor.fetchall()

            self.tableWidget.setRowCount(0)
            for num_linha, linha in enumerate(res):
                self.tableWidget.insertRow(num_linha)
                for num_col, item in enumerate(linha):
                    self.tableWidget.setItem(num_linha,num_col, QTableWidgetItem(str(item)))

        except mc.Error as e:
            print("Error", e)

    def buscar_membro(self):
        string_busca = self.lineEdit.text()
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="biblioteca"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT cpf, nome, telefone, email FROM membros WHERE cpf like '"+string_busca+"%' or nome like '"+string_busca+"%'")
            res = mycursor.fetchall()

            self.tableWidget.setRowCount(0)
            for num_linha, linha in enumerate(res):
                self.tableWidget.insertRow(num_linha)
                for num_col, item in enumerate(linha):
                    self.tableWidget.setItem(num_linha,num_col,QTableWidgetItem(str(item)))

        except mc.Error as e:
            print("Error", e)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "View Members"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Busca"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "CPF"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Nome"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Telefone"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Email"))
        self.pushButton.setText(_translate("Dialog", "Editar"))


